all: main.cpp utils.hpp
	g++ -std=c++11 main.cpp -Wall -Wextra -pedantic -g -O4 -o predictors

perceptron: perceptron.cpp utils.hpp
	g++ -std=c++11 main.cpp -Wall -Wextra -pedantic -O4 -o perceptron

run: all
