all: main.cpp utils.hpp lrucache.hpp
	g++ -std=c++17 main.cpp -Wall -Wextra -pedantic -g -o cache-sim

extra: extracred.cpp utils.hpp lrucache.hpp
	g++ -std=c++17 extracred.cpp -Wall -Wextra -pedantic -g -o extracred
